Repository Korea-Certified-Store/iOS, pull requests merged in 2023-12, with the labels that each got.

#2 Set deployment target
  .gitignore
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  KCS/KCS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  KCS/KCS/AppDelegate.swift
  KCS/KCS/Assets.xcassets/AccentColor.colorset/Contents.json
  KCS/KCS/Assets.xcassets/AppIcon.appiconset/Contents.json
  KCS/KCS/Assets.xcassets/Contents.json
  KCS/KCS/Base.lproj/LaunchScreen.storyboard
  KCS/KCS/Base.lproj/Main.storyboard
  KCS/KCS/Info.plist
  KCS/KCS/SceneDelegate.swift
  KCS/KCS/ViewController.swift
Labels: 📋 Docs, 🧱 Build

#4 Add CocoaPods Podfile
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS.xcworkspace/contents.xcworkspacedata
  KCS/Podfile
  KCS/Podfile.lock
Labels: 🧱 Build

#6 Add Alamofire
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/Podfile
  KCS/Podfile.lock
Labels: 🧱 Build

#8 Add RxSwift, RxCocoa
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/Podfile
  KCS/Podfile.lock
Labels: 🧱 Build

#10 Delete Storyboard & Set code base layout
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  KCS/KCS/Info.plist
  KCS/KCS/SceneDelegate.swift
Labels: 🧱 Build

#12 Add SwiftLint, Set Rule
  KCS/.swiftlint.yml
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/ViewController.swift
  KCS/Podfile
  KCS/Podfile.lock
Labels: 🧱 Build

#14 Seperate Directory
  KCS/.swiftlint.yml
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/AppDelegate.swift
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/.gitkeep
  KCS/KCS/Domain/.gitkeep
  KCS/KCS/Presentation/ViewController.swift
  KCS/KCS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Contents.json
  KCS/KCS/Resource/Base.lproj/LaunchScreen.storyboard
  KCS/KCS/Resource/Info.plist
  KCS/KCS/Util/.gitkeep
Labels: 🧱 Build

#16 Fix info.plist
  KCS/KCS.xcodeproj/project.pbxproj
Labels: 🛠️ Fix, 🧱 Build

#18 Install NMapsMap
  .gitignore
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/AppDelegate.swift
  KCS/KCS/Resource/Info.plist
  KCS/Podfile
  KCS/Podfile.lock
Labels: 🧱 Build

#20 Map autolayout
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/ViewController.swift
Labels: ✨ Feature, 📱 Layout
