Repository Korea-Certified-Store/iOS, pull requests merged in 2024-02, with the labels that each got.

#140 StoreListViewController 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS.xcodeproj/xcshareddata/xcschemes/KCS.xcscheme
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Entity/StoreTableViewCellContents.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/Interface/UseCase/FetchStoresUseCase.swift
  KCS/KCS/Domain/UseCase/FetchStoresUseCaseImpl.swift
  KCS/KCS/Presentation/Extension/UIStackView+clear.swift
  KCS/KCS/Presentation/Extension/UITableViewCell+Identifier.swift
  KCS/KCS/Presentation/Home/View/DetailView.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/SummaryInformationView.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreTableViewCell.swift
  KCS/KCS/Presentation/StoreList/ViewModel/Protocol/StoreListViewModel.swift
  KCS/KCS/Presentation/StoreList/ViewModel/StoreListViewModelImpl.swift
Labels: ✨ Feature, 📱 Layout

#142 SummaryInformationView 네이밍 SummaryView로 변경
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/StoreInformationView.swift
  KCS/KCS/Presentation/Home/View/SummaryView.swift
Labels: 👷‍♂️ Refactor

#147 SummaryView 이미지 scaleAspectFill으로 수정
  KCS/KCS/Presentation/Home/View/DetailView.swift
  KCS/KCS/Presentation/Home/View/SummaryView.swift
  KCS/KCS/Presentation/StoreList/View/StoreTableViewCell.swift
Labels: ✨ Feature

#145 필터 사용시 마커 선택 해제되도록 수정
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: 🛠️ Fix

#149 StoreInformation View를 ViewController로 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Domain/Entity/SummaryViewHeightCase.swift
  KCS/KCS/Presentation/Extension/UISheetPresentationController+Detent.swift
  KCS/KCS/Presentation/Extension/UIViewController+ErrorAlert.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/StoreInformationView.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeDependency.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/SummaryViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/DetailViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/SummaryViewModel.swift
  KCS/KCS/Presentation/StoreInformation/View/CertificationLabel.swift
  KCS/KCS/Presentation/StoreInformation/View/DetailView.swift
  KCS/KCS/Presentation/StoreInformation/View/OpeningHoursCellView.swift
  KCS/KCS/Presentation/StoreInformation/View/StoreInformationViewController.swift
  KCS/KCS/Presentation/StoreInformation/View/SummaryView.swift
  KCS/KCS/Presentation/StoreInformation/ViewModel/Protocol/StoreInformationViewModel.swift
  KCS/KCS/Presentation/StoreInformation/ViewModel/StoreInformationViewModelImpl.swift
Labels: ✨ Feature, 👷‍♂️ Refactor

#155 StoreListViewController 상단 Title 추가
  KCS/KCS/Presentation/Extension/UISheetPresentationController+Detent.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/StoreInformation/View/StoreInformationViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
Labels: 📱 Layout

#157 StoreListViewController present, dismiss 플로우 적용
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: ✨ Feature

#158 가게 리스트 더보기 기능 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Network/Response/Protocol/APIResponse.swift
  KCS/KCS/Data/Network/Response/StoreResponse.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Entity/FetchStores.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/Interface/UseCase/FetchRefreshStoresUseCase.swift
  KCS/KCS/Domain/UseCase/FetchRefreshStoresUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/MoreStoreButton.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeDependency.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/StoreInformation/View/StoreInformationViewController.swift
  KCS/KCS/Presentation/StoreList/ViewModel/StoreListViewModelImpl.swift
Labels: ✨ Feature, 📱 Layout

#160 24시간 영업 중인 가게 로직 변경
  KCS/KCS/Domain/Entity/OpenClosedType.swift
  KCS/KCS/Domain/UseCase/GetOpenClosedUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/StoreInformation/View/DetailView.swift
  KCS/KCS/Presentation/StoreInformation/View/SummaryView.swift
  KCS/KCS/Presentation/StoreInformation/ViewModel/StoreInformationViewModelImpl.swift
Labels: ✨ Feature, 🛠️ Fix

#163 Error Alert present 오류 해결
  KCS/KCS/Presentation/Extension/UIViewController+ErrorAlert.swift
Labels: 🛠️ Fix

#164 나침반 기능 추가
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: ✨ Feature

#166 앱 실행 후 첫 화면일 경우 모든 마커 띄우기
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/Interface/UseCase/FetchRefreshStoresUseCase.swift
  KCS/KCS/Domain/UseCase/FetchRefreshStoresUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
Labels: ✨ Feature

#169 StoreListViewController Cell 선택 구현
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Repository/Error/StoreRepositoryError.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
Labels: ✨ Feature

#171 온보딩 화면 적용
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Storage.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/OnBoarding/FifthOnboardingView.swift
  KCS/KCS/Presentation/OnBoarding/FirstOnboardingView.swift
  KCS/KCS/Presentation/OnBoarding/FourthOnboardingView.swift
  KCS/KCS/Presentation/OnBoarding/OnboardingViewController.swift
  KCS/KCS/Presentation/OnBoarding/SecondOnboardingView.swift
  KCS/KCS/Presentation/OnBoarding/ThirdOnboardingView.swift
  KCS/KCS/Resource/Assets.xcassets/OnBoarding1.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/OnBoarding1.imageset/OnBoarding1.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding1.imageset/OnBoarding1@2x.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding1.imageset/OnBoarding1@3x.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding2.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/OnBoarding2.imageset/OnBoarding2.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding2.imageset/OnBoarding2@2x.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding2.imageset/OnBoarding2@3x.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding3.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/OnBoarding3.imageset/OnBoarding3.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding3.imageset/OnBoarding3@2x.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding3.imageset/OnBoarding3@3x.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding4.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/OnBoarding4.imageset/OnBoarding4.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding4.imageset/OnBoarding4@2x.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding4.imageset/OnBoarding4@3x.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding5.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/OnBoarding5.imageset/OnBoarding5.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding5.imageset/OnBoarding5@2x.png
  KCS/KCS/Resource/Assets.xcassets/OnBoarding5.imageset/OnBoarding5@3x.png
Labels: ✨ Feature, 📱 Layout

#173 direct mode에서 재검색 버튼 클릭시 position mode normal로 변경
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: ✨ Feature

#174 현위치 버튼 및 재검색 버튼 위치 로직 조정
  KCS/KCS/Presentation/Extension/UISheetPresentationController+Detent.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
Labels: 📱 Layout

#176 다크모드 TitleBar 색상 수정
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/OnBoarding/OnboardingViewController.swift
  KCS/KCS/Presentation/StoreInformation/View/StoreInformationViewController.swift
  KCS/KCS/Presentation/StoreInformation/View/SummaryView.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
  KCS/KCS/Resource/Assets.xcassets/OnBoarding1.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/OnBoarding2.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/OnBoarding3.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/OnBoarding4.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/OnBoarding5.imageset/Contents.json
Labels: ✨ Feature, 🛠️ Fix, 📱 Layout

#178 재검색 버튼 비활성화 다크모드 대응
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Resource/Info.plist
Labels: 🛠️ Fix, 📱 Layout

#185 Release 3.0
  KCS/.swiftlint.yml
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS.xcodeproj/xcshareddata/xcschemes/KCS.xcscheme
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/Podfile.lock
Labels: 🎯 Release

#186 인터넷 연결 재시도 Alert
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/NetworkRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/NetworkRepository.swift
  KCS/KCS/Domain/UseCase/CheckNetworkStatusUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/CheckNetworkStatusUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/FetchImageUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/FetchRefreshStoresUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/FetchStoresUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/GetOpenClosedUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/GetStoreInformationUseCase.swift
  KCS/KCS/Presentation/Splash/View/SplashViewController.swift
  KCS/KCS/Presentation/Splash/ViewModel/SplashViewModelImpl.swift
  KCS/KCS/Presentation/Splash/ViewModel/protocol/SplashViewModel.swift
  KCS/KCS/Resource/Assets.xcassets/Onboarding1.imageset/Onboarding1.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding1.imageset/Onboarding1@2x.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding1.imageset/Onboarding1@3x.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding2.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Onboarding2.imageset/Onboarding2.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding2.imageset/Onboarding2@2x.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding2.imageset/Onboarding2@3x.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding3.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Onboarding3.imageset/Onboarding3.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding3.imageset/Onboarding3@2x.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding3.imageset/Onboarding3@3x.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding4.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Onboarding4.imageset/Onboarding4.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding4.imageset/Onboarding4@2x.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding4.imageset/Onboarding4@3x.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding5.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Onboarding5.imageset/Onboarding5.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding5.imageset/Onboarding5@2x.png
  KCS/KCS/Resource/Assets.xcassets/Onboarding5.imageset/Onboarding5@3x.png
Labels: ✨ Feature

#189 가게가 없을 때 필터 버튼 동작 에러 수정
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
Labels: 🛠️ Fix

#192 3.1 Release merge into main branch
  KCS/KCS.xcodeproj/project.pbxproj
Labels: 🎯 Release

#193 3.1 Release merge into develop branch
  KCS/KCS.xcodeproj/project.pbxproj
Labels: 🎯 Release

#196 UITableViewCell 선택후 뒤로가기 구현
  KCS/KCS/Presentation/Extension/UISheetPresentationController+Detent.swift
  KCS/KCS/Presentation/Extension/UIViewController+Alert.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
  KCS/KCS/Resource/Assets.xcassets/Onboarding1.imageset/Contents.json
  KCS/Podfile.lock
Labels: ✨ Feature

#199 검색 API 연결
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/DTO/SearchDTO.swift
  KCS/KCS/Data/Network/Response/Protocol/APIResponse.swift
  KCS/KCS/Data/Network/Response/RefreshStoreResponse.swift
  KCS/KCS/Data/Network/Response/SearchStoreResponse.swift
  KCS/KCS/Data/Network/Response/StoreResponse.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/UseCase/FetchSearchStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/FetchSearchStoresUseCase.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/SearchBarView.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Util/SystemImage.swift
  KCS/Podfile.lock
Labels: ✨ Feature, 📱 Layout

#201 검색 로직 구현
  KCS/KCS/Domain/UseCase/FetchSearchStoresUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
Labels: ✨ Feature

#204 Update Notification
  KCS/KCS/Presentation/Splash/View/SplashViewController.swift
  KCS/KCS/Presentation/Splash/ViewModel/SplashViewModelImpl.swift
  KCS/KCS/Presentation/Splash/ViewModel/protocol/SplashViewModel.swift
Labels: ✨ Feature

#209 가게리스트 선택 오류 수정
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
Labels: 🛠️ Fix

#212 지도 상단 검색바 Layout 적용
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/SearchBarView.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
  KCS/KCS/Resource/Assets.xcassets/SearchIcon.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/SearchIcon.imageset/Search.png
  KCS/KCS/Resource/Assets.xcassets/SearchIcon.imageset/Search@2x.png
  KCS/KCS/Resource/Assets.xcassets/SearchIcon.imageset/Search@3x.png
  KCS/KCS/Resource/Assets.xcassets/XMarkIcon.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/XMarkIcon.imageset/XMark.png
  KCS/KCS/Resource/Assets.xcassets/XMarkIcon.imageset/XMark@2x.png
  KCS/KCS/Resource/Assets.xcassets/XMarkIcon.imageset/XMark@3x.png
  KCS/KCS/Resource/Assets.xcassets/backButton.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/backButton.imageset/Vector (Stroke).png
  KCS/KCS/Resource/Assets.xcassets/backButton.imageset/Vector (Stroke)@2x.png
  KCS/KCS/Resource/Assets.xcassets/backButton.imageset/Vector (Stroke)@3x.png
  KCS/KCS/Util/SystemImage.swift
Labels: ✨ Feature, 🛠️ Fix, 📱 Layout

#211 Repository SRP 적용
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/PersistentStorage/OnboardStorage.swift
  KCS/KCS/Data/PersistentStorage/StoreStorage.swift
  KCS/KCS/Data/Repository/FetchSearchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/GetStoresRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/UseCase/FetchRefreshStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/FetchStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetRefreshStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetSearchStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetStoreInformationUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/FetchStoresUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/GetRefreshStoresUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/GetSearchStoresUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/GetStoreInformationUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/GetStoresUseCase.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCSUnitTest/FetchRefreshStoresUseCaseImplTests.swift
  KCS/KCSUnitTest/FetchStoresUseCaseImplTests.swift
  KCS/KCSUnitTest/StoreRepositoryImplTests.swift
Labels: 👷‍♂️ Refactor

#220 재검색 최대 범위 설정
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
Labels: ✨ Feature

#222 Merge Hotfix branch into develop branch
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
Labels: 🛠️ Fix

#225 뒤로가기 버튼 Layout 수정
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Resource/Assets.xcassets/BackListButton.imageset/BackListButton.png
  KCS/KCS/Resource/Assets.xcassets/BackListButton.imageset/BackListButton@2x.png
  KCS/KCS/Resource/Assets.xcassets/BackListButton.imageset/BackListButton@3x.png
  KCS/KCS/Resource/Assets.xcassets/BackListButton.imageset/Contents.json
Labels: 📱 Layout

#227 검색후 필터 적용 구현
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
Labels: ✨ Feature, 🛠️ Fix

#231 StoreListViewController 상단 title 수정
  KCS/KCS/Presentation/Extension/UISheetPresentationController+Detent.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
Labels: ✨ Feature, 📱 Layout

#229 최근 검색어 cell 별 삭제 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Search/View/RecentHistoryTableViewCell.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/RecentHistoryTableViewCellDelegate.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
Labels: ✨ Feature

#233 현 지도에서 검색어 재검색 구현
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/MoreStoreButton.swift
  KCS/KCS/Presentation/Home/View/RefreshButton.swift
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/RefreshAnimation1.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/RefreshAnimation1@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/RefreshAnimation1@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/RefreshAnimation2.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/RefreshAnimation2@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/RefreshAnimation2@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/RefreshAnimation3.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/RefreshAnimation3@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/RefreshAnimation3@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/RefreshAnimation4.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/RefreshAnimation4@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/RefreshAnimation4@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/RefreshAnimation5.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/RefreshAnimation5@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/RefreshAnimation5@3x.png
Labels: ✨ Feature, 🛠️ Fix, 📱 Layout

#235 검색 초기화 버튼 구현
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: ✨ Feature

#242 Keyboard 높이에 맞게 UITableView Constraints
  KCS/KCS/Presentation/Search/View/RecentHistoryHeaderView.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/Podfile
  KCS/Podfile.lock
Labels: 📱 Layout

#244 지도 마커가 나오는 범위 설정
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: 📱 Layout

#239 최근 검색어 전체 삭제 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Repository/SearchKeywordRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/SearchKeywordsRepository.swift
  KCS/KCS/Domain/UseCase/DeleteAllHistoryUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/DeleteAllHistoryUseCase.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Search/View/RecentHistoryHeaderView.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/CellDelegate.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/SearchViewModel.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
Labels: ✨ Feature, 🛠️ Fix

#245 가게 목록 없는 경우 StoreListView 수정
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
  KCS/KCS/Util/SystemImage.swift
Labels: 📱 Layout

#248 빈 값 검색 방지 구현
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/SearchViewModel.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
Labels: ✨ Feature

#250 Toast 위치 및 layout 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Extension/UIViewController+Alert.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/SearchViewModel.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
  KCS/KCS/Util/SystemImage.swift
Labels: ✨ Feature, 📱 Layout

#251 4.0 업데이트 이전 변경사항 적용
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
Labels: 🛠️ Fix

#254 검색시 필터버튼 일시 비활성화
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: 🛠️ Fix

#255 검색시 필터버튼 일시 비활성화
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: 🛠️ Fix

#256 Release 4.0
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: 🎯 Release

#257 Release 4.0
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/SearchKeywordRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/SearchKeywordsRepository.swift
  KCS/KCS/Domain/UseCase/DeleteAllHistoryUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/DeleteAllHistoryUseCase.swift
  KCS/KCS/Presentation/Extension/UISheetPresentationController+Detent.swift
  KCS/KCS/Presentation/Extension/UITableViewCell+Identifier.swift
  KCS/KCS/Presentation/Extension/UIViewController+Alert.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/MoreStoreButton.swift
  KCS/KCS/Presentation/Home/View/RefreshButton.swift
  KCS/KCS/Presentation/Home/View/SearchBarView.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/OnBoarding/OnboardingViewController.swift
  KCS/KCS/Presentation/Search/View/AutoCompletionTableViewCell.swift
  KCS/KCS/Presentation/Search/View/RecentHistoryHeaderView.swift
  KCS/KCS/Presentation/Search/View/RecentHistoryTableViewCell.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/CellDelegate.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/SearchViewModel.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
  KCS/KCS/Presentation/StoreInformation/View/CertificationLabel.swift
  KCS/KCS/Presentation/StoreInformation/View/DetailView.swift
  KCS/KCS/Presentation/StoreInformation/View/SummaryView.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreTableViewCell.swift
  KCS/KCS/Resource/Assets.xcassets/BackListButton.imageset/BackListButton.png
  KCS/KCS/Resource/Assets.xcassets/BackListButton.imageset/BackListButton@2x.png
  KCS/KCS/Resource/Assets.xcassets/BackListButton.imageset/BackListButton@3x.png
  KCS/KCS/Resource/Assets.xcassets/BackListButton.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/KCSGray1.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/KCSGray2.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/KCSGray3.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/RefreshAnimation1.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/RefreshAnimation1@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/RefreshAnimation1@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/RefreshAnimation2.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/RefreshAnimation2@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/RefreshAnimation2@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/RefreshAnimation3.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/RefreshAnimation3@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/RefreshAnimation3@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/RefreshAnimation4.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/RefreshAnimation4@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/RefreshAnimation4@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/RefreshAnimation5.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/RefreshAnimation5@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/RefreshAnimation5@3x.png
  KCS/KCS/Util/SystemImage.swift
  KCS/Podfile
  KCS/Podfile.lock
Labels: 🎯 Release

#262 검색어 자동 완성 API 연결
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Network/DTO/AutoCompletionDTO.swift
  KCS/KCS/Data/Network/Response/AutoCompletionResponse.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/FetchAutoCompletionRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/FetchAutoCompletionRepository.swift
  KCS/KCS/Domain/UseCase/GetAutoCompletionUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/GetAutoCompletionUseCase.swift
Labels: ✨ Feature

#264 새로운 가게 등록 요청 제목 입력 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/NewStoreRequest/View/NewStoreRequestViewController.swift
  KCS/KCS/Presentation/NewStoreRequest/View/NewStoreTextField.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/NewStoreRequestViewModelImpl.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/Protocol/NewStoreRequestViewModel.swift
  KCS/KCS/Resource/Assets.xcassets/NewStoreRequestTextFieldEdit.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/NewStoreRequestTextFieldNormal.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/UITextFieldBoldBorder.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/UITextFieldNormalBorder.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/UITextFieldWarning.colorset/Contents.json
Labels: 📱 Layout

#266 검색어 자동 완성 기능 추가
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Repository/FetchAutoCompletionRepositoryImpl.swift
  KCS/KCS/Presentation/Search/View/AutoCompletionTableViewCell.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/SearchViewModel.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
Labels: ✨ Feature, 📱 Layout

#268 카카오 주소 API 연동
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Address/View/AddressViewController.swift
Labels: ✨ Feature

#270 RequestUpdateStoreViewController 레이아웃 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/NewStoreRequest/View/NewStoreTextField.swift
  KCS/KCS/Presentation/StoreUpdateRequest/View/StoreUpdateRequestViewController.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/Protocol/StoreUpdateRequestViewModel.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/StoreUpdateRequestViewModelImpl.swift
Labels: 📱 Layout

#272 정보 수정 내용 최대 글자수 설정
  KCS/KCS/Presentation/StoreUpdateRequest/View/StoreUpdateRequestViewController.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/Protocol/StoreUpdateRequestViewModel.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/StoreUpdateRequestViewModelImpl.swift
Labels: ✨ Feature, 📱 Layout

#274 네비게이션 연결 및 완료 버튼 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/DTO/UpdateRequestDTO.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/PersistentStorage/StoreIDStorage.swift
  KCS/KCS/Data/Repository/FetchStoreIDRepositoryImpl.swift
  KCS/KCS/Data/Repository/StoreUpdateRequestRepositoryImpl.swift
  KCS/KCS/Domain/Entity/StoreUpdateRequestType.swift
  KCS/KCS/Domain/Interface/Repository/FetchStoreIDRepository.swift
  KCS/KCS/Domain/Interface/Repository/StoreUpdateRequestRepository.swift
  KCS/KCS/Domain/UseCase/FetchStoreIDUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/SetStoreIDUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/FetchStoreIDUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/SetStoreIDUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/StoreUpdateRequestUseCase.swift
  KCS/KCS/Presentation/StoreInformation/View/DetailView.swift
  KCS/KCS/Presentation/StoreInformation/View/StoreInformationViewController.swift
  KCS/KCS/Presentation/StoreUpdateRequest/View/StoreUpdateRequestViewController.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/Protocol/StoreUpdateRequestViewModel.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/StoreUpdateRequestViewModelImpl.swift
Labels: ✨ Feature, 📱 Layout

#276 불필요한 var 수정
  KCS/KCS/Data/Repository/ImageRepositoryImpl.swift
  KCS/KCS/Data/Repository/SearchKeywordRepositoryImpl.swift
  KCS/KCS/Domain/UseCase/DeleteAllHistoryUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/DeleteRecentSearchKeywordUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/FetchRecentSearchKeywordUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetSearchStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/SaveRecentSearchKeywordUseCaseImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
  KCS/KCS/Presentation/Splash/ViewModel/SplashViewModelImpl.swift
  KCS/KCS/Presentation/StoreList/ViewModel/StoreListViewModelImpl.swift
Labels: 👷‍♂️ Refactor

#279 inputView가 있는 UITextField 사용자 Edit 방지
  KCS/KCS/Presentation/NewStoreRequest/View/NewStoreTextField.swift
  KCS/KCS/Presentation/StoreUpdateRequest/View/StoreUpdateRequestViewController.swift
Labels: 🛠️ Fix

#280 RequestNewStoreViewController 레이아웃 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Domain/Entity/RequestNewStoreCertificationIsSelected.swift
  KCS/KCS/Domain/UseCase/StoreUpdateRequestUseCaseImpl.swift
  KCS/KCS/Presentation/Address/View/AddressViewController.swift
  KCS/KCS/Presentation/NewStoreRequest/View/NewStoreRequestViewController.swift
  KCS/KCS/Presentation/NewStoreRequest/View/NewStoreTextField.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/NewStoreRequestViewModelImpl.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/Protocol/NewStoreRequestViewModel.swift
  KCS/KCS/Resource/Assets.xcassets/Checkbox.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Checkbox.imageset/checkbox.png
  KCS/KCS/Resource/Assets.xcassets/Checkbox.imageset/checkbox@2x.png
  KCS/KCS/Resource/Assets.xcassets/Checkbox.imageset/checkbox@3x.png
Labels: ✨ Feature, 📱 Layout

#284 Toast 리팩토링
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Extension/UIView+removeFromSuperviewWithAnimation.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
Labels: 👷‍♂️ Refactor

#282 RequestNewStoreViewController 기능 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/DTO/NewStoreRequestDTO.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/PostNewStoreRepositoryImpl.swift
  KCS/KCS/Domain/Entity/RequestNewStoreCertificationIsSelected.swift
  KCS/KCS/Domain/Interface/Repository/PostNewStoreRepository.swift
  KCS/KCS/Domain/UseCase/PostNewStoreUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/PostNewStoreUseCase.swift
  KCS/KCS/Presentation/Extension/UIViewController+Alert.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/NewStoreRequest/View/NewStoreRequestViewController.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/NewStoreRequestViewModelImpl.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/Protocol/NewStoreRequestViewModel.swift
  KCS/KCS/Resource/Assets.xcassets/AddStoreButton.imageset/AddStoreButton.png
  KCS/KCS/Resource/Assets.xcassets/AddStoreButton.imageset/AddStoreButton@2x.png
  KCS/KCS/Resource/Assets.xcassets/AddStoreButton.imageset/AddStoreButton@3x.png
  KCS/KCS/Resource/Assets.xcassets/AddStoreButton.imageset/Contents.json
Labels: ✨ Feature, 📱 Layout

#287 Dependency 리팩토링
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeDependency.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeDependency.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/NewStoreRequest/View/AddressViewController.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/NewStoreRequestViewModelImpl.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/Protocol/NewStoreRequestDependency.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/Protocol/NewStoreRequestViewModel.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/SearchDependency.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/SearchViewModel.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
  KCS/KCS/Presentation/Splash/ViewModel/SplashViewModelImpl.swift
  KCS/KCS/Presentation/Splash/ViewModel/protocol/SplashDependency.swift
  KCS/KCS/Presentation/Splash/ViewModel/protocol/SplashViewModel.swift
  KCS/KCS/Presentation/StoreInformation/ViewModel/Protocol/StoreInformationDependency.swift
  KCS/KCS/Presentation/StoreInformation/ViewModel/Protocol/StoreInformationViewModel.swift
  KCS/KCS/Presentation/StoreInformation/ViewModel/StoreInformationViewModelImpl.swift
  KCS/KCS/Presentation/StoreList/ViewModel/Protocol/StoreListDependency.swift
  KCS/KCS/Presentation/StoreList/ViewModel/Protocol/StoreListViewModel.swift
  KCS/KCS/Presentation/StoreList/ViewModel/StoreListViewModelImpl.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/Protocol/StoreUpdateRequestDependency.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/Protocol/StoreUpdateRequestViewModel.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/StoreUpdateRequestViewModelImpl.swift
Labels: 👷‍♂️ Refactor

#290 모든 버튼 및 동작 로딩 중 다른 동작 방지
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: 🛠️ Fix

#293 애니메이션 Lottie 적용
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/RefreshButton.swift
  KCS/KCS/Resource/Animation/RefreshAnimation.json
  KCS/Podfile
  KCS/Podfile.lock
Labels: 📱 Layout

#291 서버 오류 StoreListView 오류 수정
  KCS/KCS/Data/Repository/FetchSearchStoresRepositoryImpl.swift
  KCS/KCS/Presentation/Extension/UIViewController+Alert.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/NewStoreRequest/View/NewStoreRequestViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
Labels: 🛠️ Fix

#295 인증제 필터 버튼 및 라벨 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Domain/Entity/CertificationType.swift
  KCS/KCS/Presentation/Home/View/FilterButton.swift
  KCS/KCS/Presentation/StoreInformation/View/CertificationLabel.swift
Labels: 📱 Layout

#298 서버 연결 안되는 경우 현재 키워드 재검색 버튼 애니메이션 안멈추는 오류 수정
  KCS/KCS/Presentation/Extension/UIViewController+Alert.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
Labels: 🛠️ Fix

#300 가게 정보 수정 Button Constraints 수정
  KCS/KCS/Presentation/StoreInformation/View/DetailView.swift
Labels: 🛠️ Fix, 📱 Layout

#302 뒤로가기 버튼 크기 수정
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
Labels: 📱 Layout

#305 refreshCameraPositionObserver 중복 바인딩 수정
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: 🛠️ Fix, 👷‍♂️ Refactor

#307 완료 버튼 활성화 조건 수정
  KCS/KCS/Presentation/NewStoreRequest/View/NewStoreRequestViewController.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/NewStoreRequestViewModelImpl.swift
  KCS/KCS/Presentation/NewStoreRequest/ViewModel/Protocol/NewStoreRequestViewModel.swift
Labels: 🛠️ Fix

#310 앱 반응속도 개선 [Pair Programming]
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/OnBoarding/OnboardingViewController.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/StoreInformation/View/StoreInformationViewController.swift
  KCS/KCS/Presentation/StoreInformation/View/SummaryView.swift
Labels: 🛠️ Fix

#315 자동완성 DiffableDataSource identifier hotfix
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Domain/Entity/AutoCompletionKeyword.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
Labels: 🛠️ Fix

#319 Release 5.1
  KCS/KCS.xcodeproj/project.pbxproj
Labels: 🎯 Release

#320 Release 5.1
  KCS/KCS.xcodeproj/project.pbxproj
Labels: 🎯 Release

#318 GetOpenClosedUseCase Date() 주입 리팩토링
  KCS/KCS/Domain/Entity/OpenClosedType.swift
  KCS/KCS/Domain/UseCase/GetOpenClosedUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/GetOpenClosedUseCase.swift
  KCS/KCS/Presentation/StoreInformation/ViewModel/StoreInformationViewModelImpl.swift
Labels: 👷‍♂️ Refactor

#324 SceneDelegate 가독성 리팩토링 [Pair Programming]
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/PersistentStorage/ImageCache.swift
  KCS/KCS/Data/Repository/ImageRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/FetchSearchStoresRepository.swift
  KCS/KCS/Domain/Interface/Repository/FetchStoresRepository.swift
  KCS/KCS/Domain/Interface/Repository/GetStoresRepository.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
Labels: 👷‍♂️ Refactor

#329 HomeViewModel SRP 적용
  KCS/KCS/Data/Repository/FetchStoresRepositoryImpl.swift
  KCS/KCS/Domain/Entity/FetchStores.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
Labels: 👷‍♂️ Refactor

#331 generate DiffableDataSource SRP 적용
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Extension/ApplyDiffableDataSource.swift
  KCS/KCS/Presentation/Extension/ReloadDiffableDataSource.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/StoreList/View/StoreListViewController.swift
Labels: 👷‍♂️ Refactor

#327 SearchKeywordRepository SRP 적용
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Repository/DeleteAllHistoryRepositoryImpl.swift
  KCS/KCS/Data/Repository/DeleteRecentSearchHistoryRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchRecentSearchHistoryRepositoryImpl.swift
  KCS/KCS/Data/Repository/SaveRecentSearchHistoryRepositoryImpl.swift
  KCS/KCS/Data/Repository/SearchKeywordRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/DeleteAllHistoryRepository.swift
  KCS/KCS/Domain/Interface/Repository/DeleteRecentSearchHistoryRepository.swift
  KCS/KCS/Domain/Interface/Repository/FetchRecentSearchHistoryRepository.swift
  KCS/KCS/Domain/Interface/Repository/SaveRecentSearchHistoryRepository.swift
  KCS/KCS/Domain/Interface/Repository/SearchKeywordsRepository.swift
  KCS/KCS/Domain/UseCase/DeleteAllHistoryUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/DeleteRecentSearchHistoryUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/DeleteRecentSearchKeywordUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/FetchRecentSearchHistoryUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/FetchRecentSearchKeywordUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/SaveRecentSearchHistoryUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/SaveRecentSearchKeywordUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/DeleteAllHistoryUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/DeleteRecentSearchHistoryUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/DeleteRecentSearchKeywordUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/FetchRecentSearchHistoryUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/FetchRecentSearchKeywordUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/SaveRecentSearchHistoryUseCase.swift
  KCS/KCS/Domain/UseCase/protocol/SaveRecentSearchKeywordUseCase.swift
  KCS/KCS/Presentation/Search/ViewModel/Protocol/SearchDependency.swift
  KCS/KCS/Presentation/Search/ViewModel/SearchViewModelImpl.swift
Labels: 👷‍♂️ Refactor

#334 ViewController 로직 ViewModel로 이동
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Repository/PostNewStoreRepositoryImpl.swift
  KCS/KCS/Domain/Entity/DetailViewContents.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/Search/View/SearchViewController.swift
  KCS/KCS/Presentation/StoreInformation/View/DetailView.swift
  KCS/KCS/Presentation/StoreInformation/View/StoreInformationViewController.swift
  KCS/KCS/Presentation/StoreInformation/ViewModel/Protocol/StoreInformationViewModel.swift
  KCS/KCS/Presentation/StoreInformation/ViewModel/StoreInformationViewModelImpl.swift
  KCS/KCS/Presentation/StoreUpdateRequest/ViewModel/StoreUpdateRequestViewModelImpl.swift
Labels: 👷‍♂️ Refactor

#337 Repository API 주입 리팩토링
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/APIType.swift
  KCS/KCS/Data/Network/Router.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/FetchAutoCompletionRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchSearchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/ImageRepositoryImpl.swift
  KCS/KCS/Data/Repository/PostNewStoreRepositoryImpl.swift
  KCS/KCS/Data/Repository/StoreUpdateRequestRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/FetchAutoCompletionRepository.swift
  KCS/KCS/Domain/Interface/Repository/FetchSearchStoresRepository.swift
  KCS/KCS/Domain/Interface/Repository/FetchStoresRepository.swift
  KCS/KCS/Domain/Interface/Repository/ImageRepository.swift
  KCS/KCS/Domain/Interface/Repository/PostNewStoreRepository.swift
  KCS/KCS/Domain/Interface/Repository/StoreUpdateRequestRepository.swift
Labels: 👷‍♂️ Refactor

#338 Repository API 주입 리팩토링
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/Router.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/FetchAutoCompletionRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchSearchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/ImageRepositoryImpl.swift
  KCS/KCS/Data/Repository/PostNewStoreRepositoryImpl.swift
  KCS/KCS/Data/Repository/StoreUpdateRequestRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/FetchAutoCompletionRepository.swift
  KCS/KCS/Domain/Interface/Repository/FetchSearchStoresRepository.swift
  KCS/KCS/Domain/Interface/Repository/FetchStoresRepository.swift
  KCS/KCS/Domain/Interface/Repository/ImageRepository.swift
  KCS/KCS/Domain/Interface/Repository/PostNewStoreRepository.swift
  KCS/KCS/Domain/Interface/Repository/StoreUpdateRequestRepository.swift
Labels: 👷‍♂️ Refactor

#339 SplashDependency UseCase 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCSUnitTest/FetchRefreshStoresUseCaseImplTests.swift
  KCS/KCSUnitTest/FetchStoresUseCaseImplTests.swift
  KCS/KCSUnitTest/GetStoreInformationUseCaseImplTests.swift
  KCS/KCSUnitTest/ImageRepositoryImplTests.swift
  KCS/KCSUnitTest/Mock/Repository/MockFailureNetworkRepository.swift
  KCS/KCSUnitTest/Mock/Repository/MockSuccessNetworkRepository.swift
  KCS/KCSUnitTest/MockRepository/MockFailStoreRepository.swift
  KCS/KCSUnitTest/MockRepository/MockSuccessStoreRepository.swift
  KCS/KCSUnitTest/StoreRepositoryImplTests.swift
  KCS/KCSUnitTest/UseCaseTest/Splash/CheckNetworkStatusUseCaseImplTests.swift
  KCS/Podfile
  KCS/Podfile.lock
Labels: ✅ Test

#341 Mock Server 구현
  KCS/.swiftlint.yml
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS.xcodeproj/xcshareddata/xcschemes/KCS.xcscheme
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/APIType.swift
  KCS/KCS/Data/Network/Router.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/FetchAutoCompletionRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchSearchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/ImageRepositoryImpl.swift
  KCS/KCS/Data/Repository/PostNewStoreRepositoryImpl.swift
  KCS/KCS/Data/Repository/StoreUpdateRequestRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/FetchAutoCompletionRepository.swift
  KCS/KCS/Domain/Interface/Repository/FetchSearchStoresRepository.swift
  KCS/KCS/Domain/Interface/Repository/FetchStoresRepository.swift
  KCS/KCS/Domain/Interface/Repository/ImageRepository.swift
  KCS/KCS/Domain/Interface/Repository/PostNewStoreRepository.swift
  KCS/KCS/Domain/Interface/Repository/StoreUpdateRequestRepository.swift
  KCS/KCSUnitTest/MockServer/MockURLProtocol.swift
  KCS/KCSUnitTest/MockServer/Response/.gitkeep
Labels: ✅ Test

#343 StoreListDependency UseCase 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/PersistentStorage/ImageCache.swift
  KCS/KCS/Data/Repository/FetchImageRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/FetchImageRepository.swift
  KCS/KCS/Domain/UseCase/FetchImageUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/FetchImageUseCase.swift
  KCS/KCS/Resource/Assets.xcassets/MockImage.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MockImage.imageset/MockImage.jpeg
  KCS/KCS/Resource/Assets.xcassets/MockImage.imageset/MockImage@2x.jpeg
  KCS/KCS/Resource/Assets.xcassets/MockImage.imageset/MockImage@3x.jpeg
  KCS/KCSUnitTest/Mock/Repository/MockFailureImageRepository.swift
  KCS/KCSUnitTest/Mock/Repository/MockSuccessImageRepository.swift
  KCS/KCSUnitTest/Mock/Resource/MockImage.jpeg
  KCS/KCSUnitTest/Mock/Server/MockURLProtocol.swift
  KCS/KCSUnitTest/Mock/Server/Response/.gitkeep
  KCS/KCSUnitTest/UseCaseTest/Splash/CheckNetworkStatusUseCaseImplTests.swift
  KCS/KCSUnitTest/UseCaseTest/StoreList/FetchImageUseCaseImplTests.swift
Labels: ✅ Test

#346 FetchStoresRepositoryImplTests 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Repository/FetchAutoCompletionRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchImageRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchSearchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/FetchStoresRepositoryImpl.swift
  KCS/KCS/Data/Repository/PostNewStoreRepositoryImpl.swift
  KCS/KCS/Data/Repository/StoreUpdateRequestRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/FetchStoresRepository.swift
  KCS/KCS/Domain/UseCase/GetStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/protocol/GetStoresUseCase.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Resource/MockStoreResponse.json
  KCS/KCSUnitTest/Mock/Server/MockURLProtocol.swift
  KCS/KCSUnitTest/Mock/Server/Response/FetchStoresFailureWithWrongCeritifcation.json
  KCS/KCSUnitTest/Mock/Server/Response/FetchStoresFailureWithWrongDay.json
  KCS/KCSUnitTest/Mock/Server/Response/FetchStoresSuccessWithManyStores.json
  KCS/KCSUnitTest/Mock/Server/Response/FetchStoresSuccessWithZeroStore.json
  KCS/KCSUnitTest/MockServer/Response/FetchStoresFailureWithWrongCeritifcation.json
  KCS/KCSUnitTest/MockServer/Response/FetchStoresFailureWithWrongDay.json
  KCS/KCSUnitTest/MockServer/Response/FetchStoresSuccessWithManyStores.json
  KCS/KCSUnitTest/MockServer/Response/FetchStoresSuccessWithZeroStore.json
  KCS/KCSUnitTest/RepositoryTest/FetchStoresRepositoryImplTests.swift
Labels: ✅ Test

#347 FetchImageRepositoryImpl 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Repository/FetchImageRepositoryImpl.swift
  KCS/KCSUnitTest/Mock/Repository/MockSuccessImageRepository.swift
  KCS/KCSUnitTest/Mock/Resource/MockImage.swift
  KCS/KCSUnitTest/Mock/Server/MockURLProtocol.swift
  KCS/KCSUnitTest/MockServer/Response/FetchStoresFailureWithWrongCeritifcation.json
  KCS/KCSUnitTest/MockServer/Response/FetchStoresFailureWithWrongDay.json
  KCS/KCSUnitTest/MockServer/Response/FetchStoresSuccessWithManyStores.json
  KCS/KCSUnitTest/MockServer/Response/FetchStoresSuccessWithZeroStore.json
  KCS/KCSUnitTest/RepositoryTest/FetchImageRepositoryImplTests.swift
  KCS/KCSUnitTest/RepositoryTest/FetchStoresRepositoryImplTests.swift
  KCS/KCSUnitTest/UseCaseTest/CheckNetworkStatusUseCaseImplTests.swift
  KCS/KCSUnitTest/UseCaseTest/FetchImageUseCaseImplTests.swift
Labels: ✅ Test

#349 GetStoresRepositoryImpl 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCSUnitTest/RepositoryTest/GetStoresRepositoryImplTests.swift
Labels: ✅ Test

#351 FetchSearchStoresRepositoryImpl 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCSUnitTest/Mock/Server/MockURLProtocol.swift
  KCS/KCSUnitTest/Mock/Server/Response/FetchSearchStoresFailureWithWrongCertification.json
  KCS/KCSUnitTest/Mock/Server/Response/FetchSearchStoresFailureWithWrongDay.json
  KCS/KCSUnitTest/Mock/Server/Response/FetchSearchStoresSuccessWithManyStores.json
  KCS/KCSUnitTest/Mock/Server/Response/FetchSearchStoresSuccessWithNoStore.json
  KCS/KCSUnitTest/Mock/Server/Response/FetchSearchStoresSuccessWithOneStore.json
  KCS/KCSUnitTest/RepositoryTest/FetchSearchStoresRepositoryImplTests.swift
  KCS/KCSUnitTest/RepositoryTest/FetchStoresRepositoryImplTests.swift
Labels: ✅ Test

#353 FetchRecentSearchHistoryRepositoryImpl 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCSUnitTest/Mock/Resource/MockUserDefaults.swift
  KCS/KCSUnitTest/RepositoryTest/FetchImageRepositoryImplTests.swift
  KCS/KCSUnitTest/RepositoryTest/FetchRecentSearchHistoryRepositoryImplTests.swift
  KCS/KCSUnitTest/RepositoryTest/FetchSearchStoresRepositoryImplTests.swift
  KCS/KCSUnitTest/RepositoryTest/FetchStoresRepositoryImplTests.swift
  KCS/KCSUnitTest/RepositoryTest/GetStoresRepositoryImplTests.swift
  KCS/KCSUnitTest/UseCaseTest/FetchImageUseCaseImplTests.swift
Labels: ✅ Test

#357 DeleteRecentSearchHistoryRepositoryImpl 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Repository/DeleteRecentSearchHistoryRepositoryImpl.swift
  KCS/KCSUnitTest/RepositoryTest/DeleteRecentSearchHistoryRepositoryImplTests.swift
Labels: ✅ Test

#359 DeleteAllHistoryRepositoryImpl 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCSUnitTest/RepositoryTest/DeleteAllHistoryRepositoryImplTests.swift
Labels: ✅ Test
