Repository Korea-Certified-Store/iOS, pull requests merged in 2024-01, with the labels that each got.

#25 현위치 버튼 활성화 #24
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: ✨ Feature

#26 위치 정보 권한 요청
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Resource/Info.plist
  KCS/Podfile.lock
Labels: ✨ Feature

#28 Pod 업데이트
  KCS/Podfile.lock
Labels: 🧱 Build

#30 앱 아이콘 설정
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  KCS/KCS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: ✨ Feature

#32 스플래시 화면 설정
  KCS/KCS/Resource/Assets.xcassets/KCS_logo.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/KCS_logo.imageset/Group 21.png
  KCS/KCS/Resource/Assets.xcassets/KCS_logo.imageset/Group 21@2x.png
  KCS/KCS/Resource/Assets.xcassets/KCS_logo.imageset/Group 21@3x.png
  KCS/KCS/Resource/Base.lproj/LaunchScreen.storyboard
Labels: ✨ Feature

#38 위치 정보 권한 요청 시기 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Resource/Info.plist
Labels: ✨ Feature

#40 현위치 카메라 이동
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: ✨ Feature

#41 커스텀 NMFMarker 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Domain/StoreType.swift
  KCS/KCS/Presentation/Home/View/Marker.swift
  KCS/KCS/Resource/Assets.xcassets/Marker_Exemplary_Normal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Marker_Exemplary_Normal.imageset/Subtract 1.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Exemplary_Normal.imageset/Subtract@2x 1.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Exemplary_Normal.imageset/Subtract@3x 1.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Exemplary_Selected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Marker_Exemplary_Selected.imageset/Subtract 1.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Exemplary_Selected.imageset/Subtract@2x 1.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Exemplary_Selected.imageset/Subtract@3x 1.png
  KCS/KCS/Resource/Assets.xcassets/Marker_GoodPrice_Normal .imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Marker_GoodPrice_Normal .imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/Marker_GoodPrice_Normal .imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/Marker_GoodPrice_Normal .imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/Marker_GoodPrice_Selected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Marker_GoodPrice_Selected.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/Marker_GoodPrice_Selected.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/Marker_GoodPrice_Selected.imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Safe_Normal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Marker_Safe_Normal.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Safe_Normal.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Safe_Normal.imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Safe_Selected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Marker_Safe_Selected.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Safe_Selected.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/Marker_Safe_Selected.imageset/Subtract@3x.png
Labels: ✨ Feature, 📱 Layout

#43 필터 버튼 커스텀
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Extension/UIView+SetLayerShadow.swift
  KCS/KCS/Presentation/Home/View/FilterButton.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Resource/Assets.xcassets/Exemplary.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/FilterButtonSelected.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/GoodPrice.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/KCSPrimary.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Safe.colorset/Contents.json
  KCS/KCS/Resource/ColorSet.swift
  KCS/KCS/Util/SystemImage.swift
Labels: ✨ Feature, 📱 Layout

#47 가게 정보 API 연동
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Network/DTO/RequestLocationDTO.swift
  KCS/KCS/Data/Network/DTO/StoreDTO.swift
  KCS/KCS/Data/Network/Error/JSONContentsError.swift
  KCS/KCS/Data/Network/Error/NetworkError.swift
  KCS/KCS/Data/Network/Extension/Encodable+.swift
  KCS/KCS/Data/Network/NetworkURL.swift
  KCS/KCS/Data/Network/Response/Protocol/APIResponse.swift
  KCS/KCS/Data/Network/Response/StoreResponse.swift
  KCS/KCS/Data/Network/Router.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Domain/Entity/CetificationType.swift
  KCS/KCS/Domain/Entity/Day.swift
  KCS/KCS/Domain/Entity/Location.swift
  KCS/KCS/Domain/Entity/RegularOpeningHours.swift
  KCS/KCS/Domain/Entity/Store.swift
  KCS/KCS/Domain/Entity/StoreCategory.swift
  KCS/KCS/Domain/Repository/Protocol/StoreRepository.swift
  KCS/KCS/Domain/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/StoreType.swift
  KCS/KCS/Presentation/Home/View/Marker.swift
  KCS/KCS/Resource/Info.plist
  KCS/KCS/Resource/MockStoreResponse.json
Labels: ✨ Feature

#48 현위치 버튼 이미지 커스텀
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Resource/Assets.xcassets/LocationButtonCompass.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/LocationButtonCompass.imageset/Property 1=Variant3.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonCompass.imageset/Property 1=Variant3@2x.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonCompass.imageset/Property 1=Variant3@3x.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonDirection.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/LocationButtonDirection.imageset/Property 1=Variant4.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonDirection.imageset/Property 1=Variant4@2x.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonDirection.imageset/Property 1=Variant4@3x.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonNone.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/LocationButtonNone.imageset/Property 1=Variant2.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonNone.imageset/Property 1=Variant2@2x.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonNone.imageset/Property 1=Variant2@3x.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/LocationButtonNormal.imageset/Property 1=Default.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonNormal.imageset/Property 1=Default@2x.png
  KCS/KCS/Resource/Assets.xcassets/LocationButtonNormal.imageset/Property 1=Default@3x.png
Labels: ✨ Feature, 📱 Layout

#49 요약 정보 카드 커스텀
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Network/DTO/StoreDTO.swift
  KCS/KCS/Domain/Entity/CertificationType.swift
  KCS/KCS/Domain/Entity/CetificationType.swift
  KCS/KCS/Domain/Entity/Store.swift
  KCS/KCS/Presentation/Extension/UIView+SetLayer.swift
  KCS/KCS/Presentation/Extension/UIView+SetLayerShadow.swift
  KCS/KCS/Presentation/Home/View/CertificationLabel.swift
  KCS/KCS/Presentation/Home/View/FilterButton.swift
  KCS/KCS/Presentation/Home/View/Marker.swift
  KCS/KCS/Presentation/Home/View/SummaryInformationView.swift
  KCS/KCS/Resource/Assets.xcassets/CertificationLabelText.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/ExemplaryLabel.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/GoodPriceLabel.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/KCSGray.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/KCSSecondary.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/SafeLabel.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/SwipeBar.colorset/Contents.json
  KCS/KCS/Util/SystemImage.swift
Labels: 📱 Layout

#54 마커 선택/해제 애니메이션
  KCS/KCS/Presentation/Home/View/Marker.swift
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Subtract 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Subtract@2x 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Subtract@3x 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/Subtract 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/Subtract@2x 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/Subtract@3x 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/Subtract@3x.png
Labels: ✨ Feature, 📱 Layout

#55 현재 위치 재검색 버튼 AutoLayout
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Extension/UIView+SetLayer.swift
  KCS/KCS/Presentation/Home/View/FilterButton.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/Marker.swift
  KCS/KCS/Presentation/Home/View/RefreshButton.swift
  KCS/KCS/Presentation/Home/View/SummaryInformationView.swift
  KCS/KCS/Resource/Assets.xcassets/Primary1.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Primary2.colorset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/Primary3.colorset/Contents.json
  KCS/KCS/Util/SystemImage.swift
Labels: ✨ Feature, 📱 Layout

#57 지도에 마커 표시
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/DTO/StoreDTO.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Entity/LoadedStores.swift
  KCS/KCS/Domain/Entity/Store.swift
  KCS/KCS/Domain/Entity/StoreCategory.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/Interface/UseCase/FetchStoresUseCase.swift
  KCS/KCS/Domain/Interface/UseCase/GetStoresUseCase.swift
  KCS/KCS/Domain/UseCase/FetchStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetStoresUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeDependency.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
Labels: ✨ Feature

#59 현재 위치 재검색 버튼 활성화
  KCS/KCS/Data/Network/NetworkURL.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
Labels: ✨ Feature

#61 필터 버튼 작동 구현
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/DTO/StoreDTO.swift
  KCS/KCS/Domain/Entity/CertificationType.swift
  KCS/KCS/Domain/Entity/FilteredStores.swift
  KCS/KCS/Domain/Entity/LoadedStores.swift
  KCS/KCS/Domain/Entity/Store.swift
  KCS/KCS/Domain/Interface/UseCase/GetFilteredStoresUseCase.swift
  KCS/KCS/Domain/UseCase/GetFilteredStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetStoresUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/FilterButton.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
Labels: ✨ Feature

#62 마커 선택시 요약 정보 카드 표시
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS.xcodeproj/xcshareddata/xcschemes/KCS.xcscheme
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Network/NetworkURL.swift
  KCS/KCS/Data/Repository/Error/StoreRepoError.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Entity/Day.swift
  KCS/KCS/Domain/Entity/OpenClosedType.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/Interface/UseCase/GetOpenClosedUseCase.swift
  KCS/KCS/Domain/Interface/UseCase/GetStoreInfoUseCase.swift
  KCS/KCS/Domain/UseCase/Error/OpeningHourError.swift
  KCS/KCS/Domain/UseCase/FetchStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetOpenClosedUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetStoreInfoUseCaseImpl.swift
  KCS/KCS/Presentation/Extension/Date+.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/Marker.swift
  KCS/KCS/Presentation/Home/View/SummaryInformationView.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/SummaryInformationViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/SummaryInformationViewModel.swift
Labels: ✨ Feature, 📱 Layout

#64 StoreRepositoryImpl 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS.xcodeproj/xcshareddata/xcschemes/KCS.xcscheme
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Entity/CertificationType.swift
  KCS/KCS/Domain/Entity/Location.swift
  KCS/KCS/Domain/Entity/RegularOpeningHours.swift
  KCS/KCS/Domain/Entity/Store.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/Interface/UseCase/FetchRefreshStoresUseCase.swift
  KCS/KCS/Domain/Interface/UseCase/FetchStoresUseCase.swift
  KCS/KCS/Domain/Interface/UseCase/GetFilteredStoresUseCase.swift
  KCS/KCS/Domain/UseCase/FetchRefreshStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/FetchStoresUseCaseImpl.swift
  KCS/KCS/Domain/UseCase/GetFilteredStoresUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCSUnitTest/StoreRepositoryImplTests.swift
  KCS/Podfile
  KCS/Podfile.lock
Labels: ✅ Test

#66 새로운 마커 이미지로 변경
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Property 1=Default.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Property 1=Default@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Property 1=Default@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Subtract 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Subtract@2x 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Subtract@3x 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/Subtract 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/Subtract@2x 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/Subtract@3x 1.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/모범음식점_핀.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/모범음식점_핀@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/모범음식점_핀@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Variant3@1x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Variant3@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Variant3@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/착한가격업소_핀.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/착한가격업소_핀@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/착한가격업소_핀@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/안심식당_핀.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/안심식당_핀@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/안심식당_핀@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/Subtract.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/Subtract@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/Subtract@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/안심식당_핀.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/안심식당_핀@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/안심식당_핀@3x.png
Labels: 📱 Layout

#68 URL을 통한 사진 다운로드
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/ImageCache.swift
  KCS/KCS/Data/Network/DTO/StoreDTO.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/Error/ImageRepositoryError.swift
  KCS/KCS/Data/Repository/ImageRepositoryImpl.swift
  KCS/KCS/Domain/Entity/Store.swift
  KCS/KCS/Domain/Interface/Repository/ImageRepository.swift
  KCS/KCS/Domain/Interface/UseCase/FetchImageUseCase.swift
  KCS/KCS/Domain/UseCase/FetchImageUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/SummaryInformationView.swift
  KCS/KCS/Presentation/Home/ViewModel/SummaryInformationViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/SummaryInformationViewModel.swift
Labels: ✨ Feature

#71 ViewModel input 구조 변경
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/SummaryInformationView.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/SummaryInformationViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/SummaryInformationViewModel.swift
Labels: 👷‍♂️ Refactor

#79 서버 통신 매개변수 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Network/DTO/RequestLocationDTO.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/Interface/UseCase/FetchRefreshStoresUseCase.swift
  KCS/KCS/Domain/UseCase/FetchRefreshStoresUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
Labels: 🛠️ Fix

#80 GetStoreInformationUseCaseImpl 테스트
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Data/Repository/Error/StoreRepositoryError.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/Interface/UseCase/GetStoreInformationUseCase.swift
  KCS/KCS/Domain/UseCase/GetStoreInformationUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCSUnitTest/GetStoreInformationUseCaseImplTests.swift
  KCS/KCSUnitTest/StoreRepositoryImplTests.swift
Labels: ✅ Test

#81 요약정보 UISheetPresentationController로 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/StoreInformationViewController.swift
Labels: ✨ Feature

#83 가게 영업 시간 로직 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Domain/Entity/OpenClosedContent.swift
  KCS/KCS/Domain/Entity/OpenClosedType.swift
  KCS/KCS/Domain/Interface/UseCase/GetOpenClosedUseCase.swift
  KCS/KCS/Domain/UseCase/GetOpenClosedUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/StoreInformationViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/StoreInformationViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/SummaryInformationViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/StoreInformationViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/SummaryInformationViewModel.swift
Labels: ✨ Feature

#84 재검색 최대 좌표 설정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Network/NetworkURL.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Entity/RequestLocation.swift
  KCS/KCS/Domain/Interface/Repository/StoreRepository.swift
  KCS/KCS/Domain/Interface/UseCase/FetchRefreshStoresUseCase.swift
  KCS/KCS/Domain/UseCase/FetchRefreshStoresUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Resource/Info.plist
Labels: ✨ Feature

#91 요약 정보 카드 layout 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Extension/UIFont+.swift
  KCS/KCS/Presentation/Extension/UILabel+.swift
  KCS/KCS/Presentation/Home/View/CertificationLabel.swift
  KCS/KCS/Presentation/Home/View/FilterButton.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/RefreshButton.swift
  KCS/KCS/Presentation/Home/View/StoreInformationViewController.swift
  KCS/KCS/Resource/Assets.xcassets/BasicStoreImage.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/BasicStoreImage.imageset/basicImage.png
  KCS/KCS/Resource/Assets.xcassets/BasicStoreImage.imageset/basicImage@2x.png
  KCS/KCS/Resource/Assets.xcassets/BasicStoreImage.imageset/basicImage@3x.png
  KCS/KCS/Resource/Info.plist
  KCS/KCS/Resource/font/Pretendard-Black.ttf
  KCS/KCS/Resource/font/Pretendard-Bold.ttf
  KCS/KCS/Resource/font/Pretendard-ExtraBold.ttf
  KCS/KCS/Resource/font/Pretendard-ExtraLight.ttf
  KCS/KCS/Resource/font/Pretendard-Light.ttf
  KCS/KCS/Resource/font/Pretendard-Medium.ttf
  KCS/KCS/Resource/font/Pretendard-Regular.ttf
  KCS/KCS/Resource/font/Pretendard-SemiBold.ttf
  KCS/KCS/Resource/font/Pretendard-Thin.ttf
Labels: ✨ Feature, 📱 Layout

#92 FetchRefreshStoresUseCaseImpl 테스트
  KCS/.swiftlint.yml
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Domain/UseCase/FetchRefreshStoresUseCaseImpl.swift
  KCS/KCSUnitTest/FetchRefreshStoresUseCaseImplTests.swift
  KCS/KCSUnitTest/FetchStoresUseCaseImplTests.swift
  KCS/KCSUnitTest/GetStoreInformationUseCaseImplTests.swift
  KCS/KCSUnitTest/MockRepository/MockFailStoreRepository.swift
  KCS/KCSUnitTest/MockRepository/MockSuccessStoreRepository.swift
Labels: ✅ Test

#95 마커 선택시 맨 앞으로 나오도록 구현
  KCS/KCS/Presentation/Home/View/Marker.swift
Labels: ✨ Feature

#98 현위치 버튼 및 재검색 버튼 위치 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/StoreInformationViewController.swift
  KCS/KCS/Resource/Info.plist
Labels: 🛠️ Fix

#99 배포 환경 설정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Home/View/RefreshButton.swift
  KCS/KCS/Resource/Base.lproj/LaunchScreen.storyboard
Labels: 🧱 Build

#102 이미지 파일 이름 바꾸기
  KCS/KCS/Data/Network/DTO/StoreDTO.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Domain/UseCase/GetOpenClosedUseCaseImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/Property 1=Default@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/examplary.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/examplary@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplaryNormal.imageset/examplary@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/ExemplarySelected.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/ExemplarySelected@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/ExemplarySelected@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/모범음식점_핀.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/모범음식점_핀@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerExemplarySelected.imageset/모범음식점_핀@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/GoodNormal.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/GoodNormal@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/GoodNormal@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceNormal.imageset/Variant3@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/GoodSelected.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/GoodSelected@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/GoodSelected@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/착한가격업소_핀.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/착한가격업소_핀@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerGoodPriceSelected.imageset/착한가격업소_핀@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/SafeNormal.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/SafeNormal@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/SafeNormal@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/안심식당_핀.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/안심식당_핀@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeNormal.imageset/안심식당_핀@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/SafeSelected.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/SafeSelected@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/SafeSelected@3x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/안심식당_핀.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/안심식당_핀@2x.png
  KCS/KCS/Resource/Assets.xcassets/MarkerSafeSelected.imageset/안심식당_핀@3x.png
Labels: 🛠️ Fix

#104 1.0 Release
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Resource/Info.plist
Labels: 🧱 Build

#106 요약 정보 카드 UIView로 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/StoreInformationView.swift
  KCS/KCS/Presentation/Home/View/SummaryInformationView.swift
  KCS/KCS/Presentation/Home/ViewModel/SummaryInformationViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/SummaryInformationViewModel.swift
Labels: 🛠️ Fix, 📱 Layout

#108 이슈 템플릿 적용, PR 템플릿 수정
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
Labels: 📋 Docs

#110 요약 카드 RxGesture
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/Podfile
  KCS/Podfile.lock
Labels: ✨ Feature

#116 위치 서비스가 꺼져있는 경우 현위치 버튼 회색
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: 🛠️ Fix, 📱 Layout

#120 전화 버튼 로직 수정
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Application/SceneDelegate.swift
  KCS/KCS/Domain/Entity/SummaryViewContents.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/StoreInformationView.swift
  KCS/KCS/Presentation/Home/View/SummaryInformationView.swift
  KCS/KCS/Presentation/Home/ViewModel/SummaryInformationViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/SummaryViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/SummaryInformationViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/SummaryViewModel.swift
Labels: ✨ Feature, 🛠️ Fix, 👷‍♂️ Refactor, 📱 Layout

#121 상세 정보 UIView 오류 수정
  KCS/KCS/Domain/Entity/DetailViewContents.swift
  KCS/KCS/Presentation/Home/View/DetailView.swift
  KCS/KCS/Presentation/Home/View/OpeningHoursCellView.swift
  KCS/KCS/Presentation/Home/ViewModel/DetailViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/DetailViewModel.swift
Labels: 🛠️ Fix, 👷‍♂️ Refactor, 📱 Layout

#124 DetailViewContents 및 DetailViewModel 수정 #122
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Presentation/Home/ViewModel/DetailViewModelImpl.swift
Labels: 🛠️ Fix

#125 DimView 선택시 요약정보로 이동
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
Labels: ✨ Feature, 🛠️ Fix

#127 HomeViewModel 수정 [Pair Programming]
  KCS/.swiftlint.yml
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Domain/Entity/MarkerContents.swift
  KCS/KCS/Domain/Entity/OpenClosedContent.swift
  KCS/KCS/Domain/Entity/StoreInformationViewConstraints.swift
  KCS/KCS/Presentation/Extension/NMFMyPosition+.swift
  KCS/KCS/Presentation/Home/View/DetailView.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/Marker.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeDependency.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
Labels: 👷‍♂️ Refactor

#128 로딩 애니메이션 적용
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/View/RefreshButton.swift
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/RefreshAnimation1.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/RefreshAnimation1@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation1.imageset/RefreshAnimation1@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/RefreshAnimation2.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/RefreshAnimation2@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation2.imageset/RefreshAnimation2@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/RefreshAnimation3.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/RefreshAnimation3@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation3.imageset/RefreshAnimation3@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/RefreshAnimation4.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/RefreshAnimation4@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation4.imageset/RefreshAnimation4@3x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/Contents.json
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/RefreshAnimation5.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/RefreshAnimation5@2x.png
  KCS/KCS/Resource/Assets.xcassets/RefreshAnimation5.imageset/RefreshAnimation5@3x.png
Labels: ✨ Feature, 📱 Layout

#131 Error Alert
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS/Data/Network/DTO/StoreDTO.swift
  KCS/KCS/Data/Network/Error/NetworkError.swift
  KCS/KCS/Data/Network/Extension/Encodable+.swift
  KCS/KCS/Data/Network/Router.swift
  KCS/KCS/Data/Network/StoreAPI.swift
  KCS/KCS/Data/Repository/ImageRepositoryImpl.swift
  KCS/KCS/Data/Repository/StoreRepositoryImpl.swift
  KCS/KCS/Domain/Entity/ErrorAlertMessage.swift
  KCS/KCS/Domain/Interface/UseCase/GetOpenClosedUseCase.swift
  KCS/KCS/Domain/UseCase/GetOpenClosedUseCaseImpl.swift
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/DetailViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/OpeningHourViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/SummaryViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/DetailViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/SummaryViewModel.swift
Labels: ✨ Feature

#134 필터 버튼과 검색 로직 분리
  KCS/KCS/Presentation/Home/View/HomeViewController.swift
  KCS/KCS/Presentation/Home/ViewModel/HomeViewModelImpl.swift
  KCS/KCS/Presentation/Home/ViewModel/protocol/HomeViewModel.swift
Labels: 🛠️ Fix

#135 DetailView constraint 및 font size 수정
  KCS/KCS/Presentation/Home/View/CertificationLabel.swift
  KCS/KCS/Presentation/Home/View/DetailView.swift
  KCS/KCS/Presentation/Home/View/Marker.swift
  KCS/KCS/Presentation/Home/View/SummaryInformationView.swift
Labels: 🛠️ Fix

#138 Firebase Analytics, Crashlytics
  KCS/GoogleService-Info.plist
  KCS/KCS.xcodeproj/project.pbxproj
  KCS/KCS.xcodeproj/xcshareddata/xcschemes/KCS.xcscheme
  KCS/KCS/Application/AppDelegate.swift
  KCS/Podfile
  KCS/Podfile.lock
Labels: ✨ Feature, 🧱 Build
